def generate_pdf_report(

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os
from datetime import datetime

def generate_pdf_report(
    filename="legal_report.pdf",
    mapping_data=None,
    analysis_text=None,
    ocr_text=None,
    risk_data=None,
):
    """
    Generate a professional legal PDF report with formal header, sections, and metadata footer.
    """
    os.makedirs("reports", exist_ok=True)
    path = os.path.join("reports", filename)
    c = canvas.Canvas(path, pagesize=letter)
    width, height = letter

    # Register a better font (fallback to Helvetica if not available)
    try:
        pdfmetrics.registerFont(TTFont('DejaVu', 'DejaVuSans.ttf'))
        font_main = 'DejaVu'
    except Exception:
        font_main = 'Helvetica-Bold'

    margin = 0.75 * inch
    y = height - margin
    line_height = 16

    def draw_header():
        nonlocal y
        c.setFont(font_main, 20)
        c.drawString(margin, y, "LexTransition-AI Legal Report")
        y -= 28
        c.setFont(font_main, 12)
        c.drawString(margin, y, "Automated Legal Analysis & Documentation")
        y -= 18
        c.setStrokeColor(colors.black)
        c.setLineWidth(1)
        c.line(margin, y, width - margin, y)
        y -= 18

    def draw_section(title):
        nonlocal y
        if y < margin + 80:
            c.showPage()
            y = height - margin
            draw_header()
        c.setFont(font_main, 14)
        c.setFillColor(colors.darkblue)
        c.drawString(margin, y, title)
        c.setFillColor(colors.black)
        y -= 20
        c.setStrokeColor(colors.lightgrey)
        c.setLineWidth(0.5)
        c.line(margin, y, width - margin, y)
        y -= 10

    def draw_text_block(text, font_size=11):
        nonlocal y
        c.setFont(font_main, font_size)
        for line in text.split("\n"):
            for subline in split_long_line(line, width - 2 * margin, font_main, font_size):
                if y < margin + 40:
                    c.showPage()
                    y = height - margin
                    draw_header()
                c.drawString(margin, y, subline)
                y -= line_height
        y -= 6

    def split_long_line(line, max_width, font, font_size):
        # Splits a line so it fits the page width
        words = line.split()
        lines = []
        current = ""
        for word in words:
            test = (current + " " + word).strip()
            if pdfmetrics.stringWidth(test, font, font_size) > max_width and current:
                lines.append(current)
                current = word
            else:
                current = test
        if current:
            lines.append(current)
        return lines

    def draw_footer():
        c.setFont(font_main, 9)
        c.setFillColor(colors.grey)
        footer_text = f"Generated by LexTransition-AI | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        c.drawRightString(width - margin, margin / 2, footer_text)
        c.setFillColor(colors.black)

    # --- Build PDF ---
    draw_header()

    if mapping_data:
        draw_section("Mapping Result")
        for k, v in mapping_data.items():
            draw_text_block(f"{k}: {v}")

    if analysis_text:
        draw_section("AI Analysis")
        draw_text_block(analysis_text)

    if ocr_text:
        draw_section("OCR Extracted Text")
        draw_text_block(ocr_text)

    if risk_data:
        draw_section("Risk Assessment")
        for k, v in risk_data.items():
            draw_text_block(f"{k}: {v}")

    # Footer on every page
    for page in range(1, c.getPageNumber() + 1):
        c.showPage()
        c.setPage(page)
        draw_footer()

    c.save()
    return path